config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
	resources :animals
	resources :families

   root 'welcome#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
	validates :name, :description, presence: true
	FAMILIES= ['Roundfish', 'Flatfish', 'Rockfish', 'Mammal', 'Salmon', 'Skate', 'Sculpin', 'Incidental', 'Invertebrate']
	
end

app/models/family.rb
class Family < ActiveRecord::Base
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
	def index
		@animals = Animal.all
	end

	def show
		@animal = Animal.find(params[:id])
	end

	def new
		@animal = Animal.new
	end

	def edit
		@animal=Animal.find(params[:id])
	end

	def create
		@animal = Animal.new(animal_params)

		if @animal.save
			redirect_to @animal
		else
			render 'new'
		end
	end

	def update
		@animal = Animal.find(params[:id])

		if @animal.update(animal_params)
			redirect_to @animal
		else
			render 'edit'
		end
	end

	def destroy
		@animal = Animal.find(params[:id])
		@animal.destroy

		redirect_to animals_path
	end
end

private
	def animal_params
		params.require(:animal).permit(:name, :latin_name, :thumburl, :description, :family)
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
	def index
		@families = Family.all
	end

	def show
		@family = Family.find(params[:id])
	end

	def new
		@family = Family.new
	end

	def edit
		@family=Family.find(params[:id])
	end

	def create
		@family = Family.new(family_params)

		if @family.save
			redirect_to @family
		else
			render 'new'
		end
	end

	def update
		@family = Family.find(params[:id])

		if @family.update(family_params)
			redirect_to @family
		else
			render 'edit'
		end
	end

	def destroy
		@family = Family.find(params[:id])
		@family.destroy

		redirect_to families_path
	end
end

private
	def family_params
		params.require(:family).permit(:name, :picture)
	end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
	<% if @animal.errors.any? %>
		<div id='error_explanation'>
			<h2>
				Womp womp womp. You made <%= pluralize(@animal.errors.count, "error") %> and now this animal cannae be saved!
			</h2>
			<ul>
				<% @animal.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :family %> <br>
		<%= f.collection_select :family, Animal::FAMILIES, :to_s, :to_s,
			:include_blank => true
		 %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name%>
	</p>

	<p>
		<%= f.label :latin_name %><br>
		<%= f.text_field :latin_name %>
	</p>

	<p>
		<%= f.label :thumburl %><br>
		<%= f.url_field :thumburl %>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.submit %>
	</p>

	
<% end %>

app/views/animals/edit.html.erb
<h1>we call this page.... wait for it.... animorphs! Get it? Cuz the animal, its morphing. haha.</h1>

<%= render 'form' %>

<%= link_to 'Oops, never mind', animals_path %>

app/views/animals/index.html.erb
<div class='nav-bar'>
	<ul>
		<li class ='linkz'><%= link_to 'Add a fish!', new_animal_path %></li>
	</ul>
</div>	

<h1>ALL THE FISHIES!!!!!!!!!!</h1>

<div class='row'>
	<div class='col-md-3'>
		<h3>Name</h3>
	</div>

	<div class='col-md-3'>
		<h3>Picture</h3>
	</div>

	<div class='col-md-3'>
		<h3>Description</h3>
	</div>

	<div class='col-md-3'>
		<h3>Modify</h3>
	</div>
</div>

<% @animals.each do |animal| %>
	<div class='row'>
		<div class='col-md-3'>
			<p><b><%= animal.name %></b><br><i><%= animal.latin_name %></i></p>
		</div>

		<div class='col-md-3'>
			<img src= <% if animal.thumburl.present? %>
				<%= animal.thumburl %>
			<% else %>
				<%= 'http://www.stoneburneracupuncture.com/wp-content/uploads/2014/06/question-mark-512.jpg' %>
			<% end %>
				class='thumb' >
		</div>

		<div class='col-md-3'>
			<p><%= animal.description %></p>
		</div>

		<div class='col-md-3'>
			<p class ='linkz'><%= link_to 'View', animal_path(animal) %><br><%= link_to 'Morph', edit_animal_path(animal) %><br><%= link_to 'Exterminate', animal_path(animal), method: :delete, data: { confirm: 'Destroy this fishie? You monster!'} %></p>
		</div>
	</div>
<% end %>

app/views/animals/new.html.erb
<h1>MOAR FISHIES!??!!?!?!?!??!</h1>

<%= render 'form' %>

<%= link_to 'Oops, never mind', animals_path %>

app/views/animals/show.html.erb
<h1> My animalzzzzzzz, let me show them to you...... =D</h1>

<p>
	<%= @animal.name %> <br>
	<i><%= @animal.latin_name %></i>
</p>

<img src = <% if @animal.thumburl.present? %>
				<%= @animal.thumburl %>
			<% else %>
				<%= 'http://www.stoneburneracupuncture.com/wp-content/uploads/2014/06/question-mark-512.jpg' %>
			<% end %>
	 class= 'big-pic'>

<p>
	<%= @animal.description %>
</p>

<%= link_to 'I want different fish now!', animals_path %>

app/views/families/_form.html.erb
<%= form_for @family do |f| %>
	<% if @family.errors.any? %>
		<div id='error_explanation'>
			<h2>
				Womp womp womp. You made <%= pluralize(@family.errors.count, "error") %> and now this family cannae be saved!
			</h2>
			<ul>
				<% @family.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :picture %><br>
		<%= f.url_field :picture %>
	</p>

	<p>
		<%= f.submit %>
	</p>

	
<% end %>

app/views/families/edit.html.erb
<h1>the family is changing!</h1>

<%= render 'form' %>

<%= link_to 'Oops, never mind', families_path %>

app/views/families/index.html.erb
<h1>Which kind of fish?</h1>
<div class='container'>
	<!--rounds flats and rockfish -->
	<div class='row'>
		<div class='col-md-4'>
			<a href = '#'>
				<div id='roundfish' class='fam-div'>
					<h4>ROUNDFISH</h4>
				</div>
			</a>
		</div>

		<div class='col-md-4'>
			<a href='#'>
				<div id ='flatfish' class='fam-div'>
					<h4>FLATFISH</h4>
				</div>
			</a> 
		</div>

		<div class='col-md-4'>
			<a href = '#'>
				<div id ='rockfish' class ='fam-div'>
					<h4>ROCKFISH</h4>
				</div>
			</a>
		</div>
	</div>
	<!--mammals, salmon and skates -->
	<div class='row'>
		<div class='col-md-4'>
			<a href= '#'>
				<div id='mammal' class='fam-div'>
					<h4>MAMMALS</h4>
				</div>	
			</a>
		</div>

		<div class='col-md-4'>
			<a href = '#'>
				<div id= 'salmon' class ='fam-div'>
					<h4>SALMON</h4>
				</div>
			</a>
		</div>

		<div class='col-md-4'>
			<a href = '#'>
				<div id='skate' class ='fam-div'>
					<h4>SKATES</h4>
				</div>
			</a>
		</div>
	</div>
	<!--sculpins, inverts, and incidentals-->
	<div class='row'>
		<div class='col-md-4'>
			<a href='#'>
				<div id='sculpin' class='fam-div'>
					<h4>SCULPINS</h4>
				</div>
			</a>
		</div>

		<div class = 'col-md-4'>
			<a href ='#'>
				<div id='incidental' class='fam-div'>
					<h4>INCIDENTALS</h4>
				</div>
			</a>
		</div>

		<div class='col-md-4'>
			<a href='#'>
				<div id ='invertebrate' class='fam-div'>
					<h4>INVERTS</h4>
				</div>
			</a>
		</div>
	</div>
</div>

app/views/families/new.html.erb
<h1>welcome to the family!</h1>

<%= render 'form' %>

<%= link_to 'Oops, never mind', families_path %>

app/views/families/show.html.erb
<h1> All in the family!!</h1>

<p>
	<%= @family.name %>
</p>

<img src = <%= @family.picture %> class= big-pic>



<%= link_to 'I want different fish now!', families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FishGuide</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
	<div class='jumbotron'>
		<div class='container'>
			<h1>Welcome to my awesome North Pacific fish guide!!!!!!!!!!!!</h1>
		</div>
	</div>

<%= link_to 'All the Animals!!', controller: 'animals' %>